# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
console_title_template: "{{.Shell}} in {{.Folder}}"
transient_prompt:
  background: "transparent"
  foreground: "#ffffff"
  template: "{{if .Root}}#{{else}}${{end}} "
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: session
        template: " {{if .Root}}󰒃 {{end}}{{.UserName}} "
        style: diamond
        leading_diamond: 
        foreground: "#ffffff"
        background: "#2e9599"
        background_templates:
          - "{{if .Root}}#dc322f{{end}}"
      - type: path
        template: "   {{.Path}} "
        properties:
          style: agnoster_short
          max_depth: 3
          folder_separator_icon: "  "
          home_icon: 
          mapped_locations:
            'C:\Users\rkozak\git': 󰊢
            'C:\Users\rkozak\Downloads': 
            'C:\Users\rkozak\Music': 󰝚
            'C:\Users\rkozak\Videos': 
            'C:\Users\rkozak\OneDrive - Charter Telecom Inc\Documents': 󰧮
            'C:\Users\rkozak\OneDrive - Charter Telecom Inc\Pictures': 
        style: powerline
        powerline_symbol: 
        foreground: "#ffffff"
        background: "#477dda"
      - type: git
        template: " {{.UpstreamIcon}}{{.HEAD}}{{if .BranchStatus}} {{.BranchStatus}}{{end}}{{if .Working.Changed}}  {{.Working.String}}{{end}}{{if and (.Working.Changed) (.Staging.Changed)}} |{{end}}{{if .Staging.Changed}}  {{.Staging.String}}{{end}}{{if gt .StashCount 0}}  {{.StashCount}}{{end}} "
        properties:
          fetch_status: true
          fetch_stash_count: true
          fetch_upstream_icon: true
          branch_max_length: 25
        style: powerline
        powerline_symbol: 
        foreground: "#193549"
        background: "#fffb38"
        background_templates:
          - "{{if or (.Working.Changed) (.Staging.Changed)}}#ff9248{{end}}"
          - "{{if and (gt .Ahead 0) (gt .Behind 0)}}#ff4500{{end}}"
          - "{{if gt .Ahead 0}}#b388ff{{end}}"
          - "{{if gt .Behind 0}}#b388ff{{end}}"
      - type: python
        template: "  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} "
        properties:
          display_default: false
          display_mode: files
          fetch_virtual_env: false
        style: powerline
        powerline_symbol: 
        foreground: "#111111"
        background: "#ffde57"
      - type: go
        template: " 󰟓 {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} "
        style: powerline
        powerline_symbol: 
        foreground: "#111111"
        background: "#8ed1f7"
      - type: node
        template: " 󰎙 {{if .PackageManagerIcon}}{{.PackageManagerIcon}} {{end}}{{.Full}} "
        properties:
          fetch_package_manager: true
        style: powerline
        powerline_symbol: 
        foreground: "#ffffff"
        background: "#6ca35e"
      - type: npm
        template: "  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} "
        properties:
          fetch_package_manager: true
        style: powerline
        powerline_symbol: 
        foreground: "#ffffff"
        background: "#6ca35e"
      - type: aws
        template: " 󰸏 {{.Profile}}{{if .Region}}@{{.Region}}{{end}} "
        style: powerline
        powerline_symbol: 
        foreground: "#ffffff"
        background: "#ffa400"
      - type: az
        template: " ﴃ󰠅 {{.EnvironmentName}}{{if .Name}}{{.Name}}{{end}} "
        style: powerline
        powerline_symbol: 
        foreground: "#000000"
        background: "#9ec3f0"
      - type: azfunc
        template: " 󰠅 {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} "
        style: powerline
        powerline_symbol: 
        foreground: "#ffffff"
        background: "#FEAC19"
      - type: rust
        template: "  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} "
        style: powerline
        powerline_symbol: 
        foreground: "#193549"
        background: "#99908a"
      - type: docker
        template: " 󰡨 {{.Context}} "
        style: powerline
        powerline_symbol: 
        foreground: "#000000"
        background: "#0b59e7"
      - type: kubectl
        template: " 󱃾 {{.Context}} :: {{if .Namespace}}{{.Namespace}}{{else}}default{{end}} "
        style: powerline
        powerline_symbol: 
        foreground: "#000000"
        background: "#ebcc34"
      - type: executiontime
        template: "  {{.FormattedMs}} "
        properties:
          always_enabled: true
        style: powerline
        powerline_symbol: 
        foreground: "#ffffff"
        background: "#83769c"
      - type: exit
        template: " {{if ne .Code 0}} {{.Code}}{{end}} "
        properties:
          always_enabled: true
        style: diamond
        trailing_diamond: 
        foreground: "#ffffff"
        background: "#00897b"
        background_templates:
          - "{{if ne .Code 0}}#e91e63{{end}}"
      - type: upgrade
        template: " 󰚰 {{.Version}} "
        style: diamond
        invert_powerline: true
        leading_diamond: 
        trailing_diamond: 
        foreground: "#111111"
        background: "#ffd664"
  - type: prompt
    alignment: right
    segments:
      - type: sysinfo
        template: "  {{round .PhysicalPercentUsed .Precision}} "
        properties:
          precision: 2
        style: diamond
        invert_powerline: true
        leading_diamond: 
        foreground: "#ffffff"
        background: "#546e7a"
      - type: battery
        template: "{{if .Error}} {{.Error}} {{else}} {{.Icon}}{{.Percentage}} {{end}}"
        properties:
          charged_icon: "󰁹 "
          charging_icon: "󰢝 "
          discharging_icon: "󰁾 "
          not_charging_icon: "󱃌 "
        style: powerline
        invert_powerline: true
        powerline_symbol: 
        foreground: "#ffffff"
        background: "#f36943"
        background_templates:
          - '{{if eq "Charging" .State.String}}#40c4ff{{end}}'
          - '{{if eq "Discharging" .State.String}}#ff5722{{end}}'
          - '{{if eq "Full" .State.String}}#4caf50{{end}}'
      - type: time
        template: ' {{ dateInZone "15:04:05 UTC" .CurrentDate "UTC" }} '
        style: diamond
        invert_powerline: true
        trailing_diamond: 
        foreground: "#ffffff"
        background: "#2e9599"
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        template: "{{if .Root}}#{{else}}${{end}}"
        background: "transparent"
        foreground: "#ffffff"
